# compose development configuration

version: '3'

services:
  nginx:
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
    depends_on:
      - web
      - server
  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  server:
    container_name: {conf.PROJECT_NAME}_dev_server
    volumes:
      - {conf.SERVER}:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
  web:
    container_name: {conf.PROJECT_NAME}_dev_web
    volumes:
      - {conf.WEB}:/usr/src/app
    command: npm start
    build:
      context: {conf.WEB}
      dockerfile: Dockerfile
    image: {conf.PROJECT_NAME}_web
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - server