version: '3'

services:
  db:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  server:
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 8000

  web:
    volumes:
      - .:/usr/src/app
    command: npm start